// Generated by CoffeeScript 1.7.1
var Basics, Browsers, Examples, Flexbox, Introductions, ORM, Resources, Spine,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

require('lib/setup');

Spine = require('spine');

ORM = require('orm');

Introductions = require('controllers/introductions');

Basics = require('controllers/basics');

Examples = require('controllers/examples');

Browsers = require('controllers/browsers');

Resources = require('controllers/resources');

Flexbox = (function(_super) {
  __extends(Flexbox, _super);

  Flexbox.include(ORM.state);

  function Flexbox() {
    Flexbox.__super__.constructor.apply(this, arguments);
    Spine.Route.setup();
    this.notification.hide();
  }

  Flexbox.prototype.el = '#content';

  Flexbox.prototype.elements = {
    '.notification-loading': 'notification'
  };

  Flexbox.prototype.controllers = {
    introduction: Introductions,
    basic: Basics,
    example: Examples,
    browser: Browsers,
    resource: Resources
  };

  Flexbox.prototype.routes = {
    '/introduction': 'introduction',
    '/basics': 'basic',
    '/examples': 'example',
    '/browsers': 'browser',
    '/resources': 'resource'
  };

  Flexbox.prototype["default"] = 'introduction';

  return Flexbox;

})(Spine.Stack);

module.exports = Flexbox;
