// Generated by CoffeeScript 1.7.1
var ORM;

ORM = {
  state: {
    activate: function() {
      this.el.addClass('controller-active');
      return this.el.removeClass('controller-loading');
    },
    deactivate: function() {
      this.el.removeClass('controller-active');
      return this.el.addClass('controller-loading');
    }
  },
  tabulate: {
    tabulate: function() {
      this.tabs = this.el.find('.nav-tabs');
      return this.tabs.find('a').on('click', $.proxy(this.setTab, this));
    },
    setTab: function(e) {
      var link;
      link = $(e.currentTarget);
      e.preventDefault();
      this.tabs.find('.active').removeClass('active');
      link.parent().addClass('active');
      this.el.find('.tab-content-active').removeClass('tab-content-active');
      return this.el.find(link.attr('href')).addClass('tab-content-active');
    }
  }
};

module.exports = ORM;
