// Generated by CoffeeScript 1.7.1
var Basics, ORM, Spine, view,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Spine = require('spine');

ORM = require('orm');

view = require('views/basic');

Basics = (function(_super) {
  __extends(Basics, _super);

  Basics.include(ORM.state);

  Basics.include(ORM.tabulate);

  function Basics() {
    Basics.__super__.constructor.apply(this, arguments);
    this.view = view;
    this.html(this.view);
    this.tabulate();
  }

  Basics.prototype.el = '#basics';

  return Basics;

})(Spine.Controller);

module.exports = Basics;
