// Generated by CoffeeScript 1.7.1
var ORM, Spine, Supports, view,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Spine = require('spine');

ORM = require('orm');

view = require('views/browser');

Supports = (function(_super) {
  __extends(Supports, _super);

  Supports.include(ORM.state);

  function Supports() {
    Supports.__super__.constructor.apply(this, arguments);
    this.view = view;
    this.html(this.view);
  }

  Supports.prototype.el = '#browsers';

  return Supports;

})(Spine.Controller);

module.exports = Supports;
