// Generated by CoffeeScript 1.7.1
var Introductions, ORM, Spine, view,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Spine = require('spine');

ORM = require('orm');

view = require('views/introduction');

Introductions = (function(_super) {
  __extends(Introductions, _super);

  Introductions.include(ORM.state);

  function Introductions() {
    Introductions.__super__.constructor.apply(this, arguments);
    this.view = view;
    this.html(this.view);
  }

  Introductions.prototype.el = '#introduction';

  return Introductions;

})(Spine.Controller);

module.exports = Introductions;
