// Generated by CoffeeScript 1.7.1
var ORM, Resources, Spine, view,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Spine = require('spine');

ORM = require('orm');

view = require('views/resource');

Resources = (function(_super) {
  __extends(Resources, _super);

  Resources.include(ORM.state);

  function Resources() {
    Resources.__super__.constructor.apply(this, arguments);
    this.view = view;
    this.html(this.view);
  }

  Resources.prototype.el = '#resources';

  return Resources;

})(Spine.Controller);

module.exports = Resources;
